---
- name: Fetch user and group information
  ansible.builtin.getent:
    database: passwd

- name: Set user password if user exists
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    create_home: "{{ user.create_home | default(true) }}"
    home: "{{ '/nonexistent' if not (user.create_home | default(true)) else omit }}"
  become: true
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: user
  when:
    - user.password is defined
    - getent_passwd[user.name] is defined
